-- Run as SYS from container init process
CREATE USER GVI IDENTIFIED BY gvi;
GRANT CONNECT, RESOURCE TO GVI;

CREATE USER GOM IDENTIFIED BY gom;
GRANT CONNECT, RESOURCE TO GOM;

GRANT UNLIMITED TABLESPACE TO GVI;
GRANT UNLIMITED TABLESPACE TO GOM;
