ALTER SESSION SET CURRENT_SCHEMA = GOM;

CREATE TABLE OE_ORDER_HEADERS_ALL (
  HEADER_ID NUMBER PRIMARY KEY,
  ORDER_NUMBER VARCHAR2(30 BYTE),
  CUST_PO_NUMBER VARCHAR2(50 BYTE),
  ORDERED_DATE DATE,
  FLOW_STATUS_CODE VARCHAR2(30 BYTE),
  CREATION_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE OE_ORDER_LINES_ALL (
  LINE_ID NUMBER PRIMARY KEY,
  HEADER_ID NUMBER NOT NULL,
  LINE_NUMBER VARCHAR2(30 BYTE),
  INVENTORY_ITEM_ID NUMBER,
  ORDERED_QUANTITY NUMBER,
  FLOW_STATUS_CODE VARCHAR2(30 BYTE),
  REQUEST_DATE DATE,
  CREATION_DATE DATE DEFAULT SYSDATE,
  CONSTRAINT FK_OE_LINES_HEADER FOREIGN KEY (HEADER_ID)
    REFERENCES OE_ORDER_HEADERS_ALL(HEADER_ID)
);

CREATE INDEX IX_GOM_HEADERS_PO ON OE_ORDER_HEADERS_ALL (CUST_PO_NUMBER);
CREATE INDEX IX_GOM_LINES_HEADER ON OE_ORDER_LINES_ALL (HEADER_ID);

INSERT INTO OE_ORDER_HEADERS_ALL (
  HEADER_ID, ORDER_NUMBER, CUST_PO_NUMBER, ORDERED_DATE, FLOW_STATUS_CODE, CREATION_DATE
) VALUES (
  910001, 'GOM-1000841454', '5204-8477833', TO_DATE('19-FEB-26 08.25.00','DD-MON-RR HH24.MI.SS'), 'BOOKED', TO_DATE('19-FEB-26 08.25.00','DD-MON-RR HH24.MI.SS')
);

INSERT INTO OE_ORDER_LINES_ALL (
  LINE_ID, HEADER_ID, LINE_NUMBER, INVENTORY_ITEM_ID, ORDERED_QUANTITY, FLOW_STATUS_CODE, REQUEST_DATE, CREATION_DATE
) VALUES (
  920001, 910001, '1', 1000841454, 4, 'AWAITING_SHIPPING', TO_DATE('19-FEB-26 23.59.00','DD-MON-RR HH24.MI.SS'), TO_DATE('19-FEB-26 08.26.00','DD-MON-RR HH24.MI.SS')
);

COMMIT;
